### PR TITLE
add more information about launch variables and an example

### PR DESCRIPTION
**Pull request by lublak**

### CODE REVIEW

**Comment by lublak** [comment]
I think they are very useful examples. I also find the reference to the library useful. (I actively use the second example).

**Comment by mike-lischke** [comment]
@lublak please sign your commits in the PR (DCO).

**Review by mike-lischke — COMMENTED** [review]
Nice information. It probably deserves an own chapter about how to improve the debugging experience.

**Comment by lublak** [comment]
> @lublak please sign your commits in the PR (DCO).

@mike-lischke dco? 😕 

"This commit was created on GitHub.com and signed with GitHub’s verified signature."

**Comment by mike-lischke** [comment]
Follow the Details link for the DCO row in the GH action window below. DCO is required to accept PRs.

**Comment by lublak** [comment]
@mike-lischke done :)

**Comment by mike-lischke** [comment]
Something with your signature is still not ok. I cannot merge. [Phind](https://www.phind.com/search?cache=l0a87fae6kqr4y7zpidd8nbr) "believes" the signature format could be wrong.

**Pull request merged**
