### PR TITLE
Removing angle brackets from the language configuration

### PR DESCRIPTION
**Pull request by racz16**
VS Code uses the brackets listed in the `antlr.configuration.json` file's `brackets` property to color the corresponding brackets with the same color. However, if it finds a closing bracket, without an opening one, it colors the bracket red. When we send a token to a channel, the angle bracket of `->` becomes red. This is why I removed angle brackets from the language configuration.
Before:
before
After:
after

### CODE REVIEW

**Comment by mike-lischke** [comment]
This depends also on the theme. The main problem is that the arrow and other syntactic elements are not handled by most themes, which is why I added one which does. That looks then so:

Bildschirmfoto 2024-03-24 um 11 13 12

but of course not everyone likes this.

Please check the DCO (follow the Details link)

**Comment by racz16** [comment]
Yes, I think your theme is good, but people need to switch to it manually or they just don't want to use it. I fixed the commit.

**Comment by mike-lischke** [comment]
Please sign your commit if you want it to be merged.

**Comment by mike-lischke** [comment]
@racz16 Last chance to sign your PR.

**Comment by mike-lischke** [comment]
Thanks!

**Pull request merged**
